### ISSUE TITLE
upload any small projects

### ISSUE THREAD

**Issue by pixobia** [pixobia/projects-for-hacktoberfest#1]
projects that are uploaded will be accepted,and you can contribute to hacktoberfest.

**Comment by godwin-04** [comment]
kindly assign this to me @pixobia 
i would upload python program for rock, paper, scissors

**Comment by rohitsinghind** [comment]
hey, can you assign this to me, I upload reactJS chatroom Project using firebase

**Comment by ELIJAHJOHNNY** [comment]
Hi @pixobia how about a small mini blog having Json server running as a backend having a feature to post, edit and delete blogs. Is that okay?

**Comment by pixobia** [comment]
> @pixobia Do we need to be assigned to this issue to open Pull Requests ?

no you can upload PR ,i will merge it...

**Comment by pixobia** [comment]
@godwin-04 @riddhitech @ELIJAHJOHNNY @octosapien @rohitsinghind you guys all can upload your projects,i well merge them,but create a spreate folders and sub branch while uploading the projects,do it fast guys since time for hactoberfest is going to end soon!All the best...
